/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as authenticatedProjectsRouteRouteImport } from './routes/(authenticated)/projects/route'
import { Route as authenticatedProjectsIndexRouteImport } from './routes/(authenticated)/projects/index'
import { Route as authenticatedProjectsProjectIdIndexRouteImport } from './routes/(authenticated)/projects/$projectId/index'
import { Route as authenticatedProjectsProjectIdMembersRouteImport } from './routes/(authenticated)/projects/$projectId/members'
import { Route as authenticatedProjectsProjectIdApiKeysRouteImport } from './routes/(authenticated)/projects/$projectId/api-keys'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const authenticatedProjectsRouteRoute =
  authenticatedProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedProjectsIndexRoute =
  authenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedProjectsRouteRoute,
  } as any)
const authenticatedProjectsProjectIdIndexRoute =
  authenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => authenticatedProjectsRouteRoute,
  } as any)
const authenticatedProjectsProjectIdMembersRoute =
  authenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/$projectId/members',
    path: '/$projectId/members',
    getParentRoute: () => authenticatedProjectsRouteRoute,
  } as any)
const authenticatedProjectsProjectIdApiKeysRoute =
  authenticatedProjectsProjectIdApiKeysRouteImport.update({
    id: '/$projectId/api-keys',
    path: '/$projectId/api-keys',
    getParentRoute: () => authenticatedProjectsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/projects': typeof authenticatedProjectsRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/': typeof AuthIndexRoute
  '/projects/': typeof authenticatedProjectsIndexRoute
  '/projects/$projectId/api-keys': typeof authenticatedProjectsProjectIdApiKeysRoute
  '/projects/$projectId/members': typeof authenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/': typeof authenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth': typeof AuthIndexRoute
  '/projects': typeof authenticatedProjectsIndexRoute
  '/projects/$projectId/api-keys': typeof authenticatedProjectsProjectIdApiKeysRoute
  '/projects/$projectId/members': typeof authenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId': typeof authenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(authenticated)/projects': typeof authenticatedProjectsRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/': typeof AuthIndexRoute
  '/(authenticated)/projects/': typeof authenticatedProjectsIndexRoute
  '/(authenticated)/projects/$projectId/api-keys': typeof authenticatedProjectsProjectIdApiKeysRoute
  '/(authenticated)/projects/$projectId/members': typeof authenticatedProjectsProjectIdMembersRoute
  '/(authenticated)/projects/$projectId/': typeof authenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/auth/signin'
    | '/auth/'
    | '/projects/'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId/members'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth'
    | '/projects'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId/members'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/auth'
    | '/(authenticated)/projects'
    | '/auth/signin'
    | '/auth/'
    | '/(authenticated)/projects/'
    | '/(authenticated)/projects/$projectId/api-keys'
    | '/(authenticated)/projects/$projectId/members'
    | '/(authenticated)/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(authenticated)/projects': {
      id: '/(authenticated)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authenticatedProjectsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/projects/': {
      id: '/(authenticated)/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof authenticatedProjectsIndexRouteImport
      parentRoute: typeof authenticatedProjectsRouteRoute
    }
    '/(authenticated)/projects/$projectId/': {
      id: '/(authenticated)/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof authenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof authenticatedProjectsRouteRoute
    }
    '/(authenticated)/projects/$projectId/members': {
      id: '/(authenticated)/projects/$projectId/members'
      path: '/$projectId/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof authenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof authenticatedProjectsRouteRoute
    }
    '/(authenticated)/projects/$projectId/api-keys': {
      id: '/(authenticated)/projects/$projectId/api-keys'
      path: '/$projectId/api-keys'
      fullPath: '/projects/$projectId/api-keys'
      preLoaderRoute: typeof authenticatedProjectsProjectIdApiKeysRouteImport
      parentRoute: typeof authenticatedProjectsRouteRoute
    }
  }
}

interface authenticatedProjectsRouteRouteChildren {
  authenticatedProjectsIndexRoute: typeof authenticatedProjectsIndexRoute
  authenticatedProjectsProjectIdApiKeysRoute: typeof authenticatedProjectsProjectIdApiKeysRoute
  authenticatedProjectsProjectIdMembersRoute: typeof authenticatedProjectsProjectIdMembersRoute
  authenticatedProjectsProjectIdIndexRoute: typeof authenticatedProjectsProjectIdIndexRoute
}

const authenticatedProjectsRouteRouteChildren: authenticatedProjectsRouteRouteChildren =
  {
    authenticatedProjectsIndexRoute: authenticatedProjectsIndexRoute,
    authenticatedProjectsProjectIdApiKeysRoute:
      authenticatedProjectsProjectIdApiKeysRoute,
    authenticatedProjectsProjectIdMembersRoute:
      authenticatedProjectsProjectIdMembersRoute,
    authenticatedProjectsProjectIdIndexRoute:
      authenticatedProjectsProjectIdIndexRoute,
  }

const authenticatedProjectsRouteRouteWithChildren =
  authenticatedProjectsRouteRoute._addFileChildren(
    authenticatedProjectsRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedProjectsRouteRoute: typeof authenticatedProjectsRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedProjectsRouteRoute: authenticatedProjectsRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
